language: node_js
node_js:
  - "4"

node_js:
  - stable

install:
  - npm install

script:
  - npm run cover
  
# Send coverage data to Coveralls
after_script: "nyc report --reporter=text-lcov | coveralls"